# Generated by Django 3.2.4 on 2021-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proveedores_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='moneda',
            field=models.CharField(choices=[['pesos', 'Pesos'], ['dolares', 'Dólares']], max_length=8, verbose_name='moneda'),
        ),
    ]
