# Generated by Django 3.2.4 on 2021-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_proveedores_numero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='numero_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de Id'),
        ),
    ]
